{% set name = "questionary" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a050fdbb81406cddca679a6f492c6272da90cb09988963817828f697cf091c55

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<3.10
    - pip
    - poetry >=1.0.5
  run:
    - python >=3.6,<3.10
    - prompt_toolkit >=2.0,<4.0

test:
  imports:
    - questionary
    - questionary.prompts

about:
  home: https://github.com/tmbo/questionary
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python library to build pretty command line prompts.
  description: Easy to use multi-select lists, confirmations, free text prompts...
  doc_url: https://github.com/tmbo/questionary#documentation
  dev_url: https://github.com/tmbo/questionary

extra:
  recipe-maintainers:
    - apeltzer
    - ewels
